language: java # to trigger the build on JVM worker ('language: scala' works the same)
env:
  - PLAY_VERSION="2.1.1" # Latest 2.1.x
before_script:
  - wget http://downloads.typesafe.com/play/2.1.1/play-${PLAY_VERSION}.zip
  - unzip -q play-${PLAY_VERSION}.zip
script: play-${PLAY_VERSION}/play test
notifications:
  # Email notifications are disabled to not annoy anybody.
  # See http://about.travis-ci.org/docs/user/build-configuration/ to learn more
  # about configuring notification recipients and more.
  email: false